In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
import inflect
import string, re
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.tokenize.regexp import WordPunctTokenizer, WhitespaceTokenizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag, ne_chunk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('maxent_ne_chunker')
nltk.download('words')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

# **1. Bag of Words (BOG):**

In [2]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [3]:
def To_Lower(st):
  return st.lower()

def Convert_numbers_To_string(st):
  q = inflect.engine()
  temp_str = st.split()
  new_str = []
  for word in temp_str:
    if word.isdigit():
      temp = q.number_to_words(word)
      new_str.append(temp)
    else:
      new_str.append(word)
  final_str = ' '.join(new_str)
  return final_str
        
def Remove_Punctuation(st):
  translator = str.maketrans('', '', string.punctuation)
  return st.translate(translator)

def To_Tokenize(st):
  return word_tokenize(st)

def Remove_stop_of_words(st):
  stop_words = set(stopwords.words('english'))
  st = [word for word in st if word not in stop_words]
  return st

def To_Stemming(st):
  porter = PorterStemmer()
  stm = [porter.stem(word) for word in st]
  return stm



def Word_Count(st):
  st = ' '.join(st)
  tokens = WhitespaceTokenizer().tokenize(st)
  vocab = set(tokens)
  return vocab


In [4]:
para = To_Lower(paragraph)
para = Convert_numbers_To_string(para)
para = Remove_Punctuation(para)
para = To_Tokenize(para)
para = Remove_stop_of_words(para)
para = To_Stemming(para)
corpus = Word_Count(para)
corpus

{'1857',
 'achiev',
 'alexand',
 'also',
 'among',
 'anyon',
 'area',
 'believ',
 'brahm',
 'british',
 'build',
 'came',
 'captur',
 'career',
 'close',
 'come',
 'conquer',
 'consid',
 'cultur',
 'dept',
 'develop',
 'dhawan',
 'done',
 'dr',
 'dutch',
 'econom',
 'enforc',
 'fall',
 'father',
 'fifti',
 'first',
 'five',
 'fortun',
 'four',
 'free',
 'freedom',
 'french',
 'gdp',
 'global',
 'go',
 'good',
 'got',
 'grab',
 'great',
 'greek',
 'growth',
 'handinhand',
 'histori',
 'incorrect',
 'independ',
 'india',
 'invad',
 'lack',
 'land',
 'level',
 'life',
 'loot',
 'lucki',
 'materi',
 'mileston',
 'militari',
 'mind',
 'mogul',
 'must',
 'nation',
 'nuclear',
 'nurtur',
 'one',
 'onward',
 'opportun',
 'othersthat',
 'peopl',
 'percent',
 'portugues',
 'poverti',
 'power',
 'prakash',
 'professor',
 'protect',
 'rate',
 'recognis',
 'respect',
 'sarabhai',
 'satish',
 'second',
 'see',
 'selfassur',
 'selfconfid',
 'selfreli',
 'space',
 'stand',
 'start',
 'strength',
 'str

In [5]:
len(corpus)

117

In [6]:
cv = CountVectorizer(max_features=1000)
X = cv.fit_transform(corpus)
X

<117x116 sparse matrix of type '<class 'numpy.int64'>'
	with 116 stored elements in Compressed Sparse Row format>

In [7]:
X = X.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [9]:
len(X), X.shape

(117, (117, 116))

In [10]:
BOG = pd.DataFrame()
BOG['Corpus'] = list(word for word in corpus)
BOG['Vectorization'] = [vector for vector in X]

BOG.head(10)

Corpus                                      Vectorization
0         gdp  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
1        area  [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...
2    thousand  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3       today  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4          go  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5         way  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
6        life  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
7       fifti  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
8       build  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...
9  othersthat  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [11]:
BOG.iloc[0]

Corpus                                                         gdp
Vectorization    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 0, dtype: object

In [12]:
BOG.iloc[0][1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

# **2. TF-IDF:**

In [13]:
paragraph

'I have three visions for India. In 3000 years of our history, people from all over \n               the world have come and invaded us, captured our lands, conquered our minds. \n               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,\n               the French, the Dutch, all of them came and looted us, took over what was ours. \n               Yet we have not done this to any other nation. We have not conquered anyone. \n               We have not grabbed their land, their culture, \n               their history and tried to enforce our way of life on them. \n               Why? Because we respect the freedom of others.That is why my \n               first vision is that of freedom. I believe that India got its first vision of \n               this in 1857, when we started the War of Independence. It is this freedom that\n               we must protect and nurture and build on. If we are not free, no one will respect us.\n              

In [14]:
corpus

{'1857',
 'achiev',
 'alexand',
 'also',
 'among',
 'anyon',
 'area',
 'believ',
 'brahm',
 'british',
 'build',
 'came',
 'captur',
 'career',
 'close',
 'come',
 'conquer',
 'consid',
 'cultur',
 'dept',
 'develop',
 'dhawan',
 'done',
 'dr',
 'dutch',
 'econom',
 'enforc',
 'fall',
 'father',
 'fifti',
 'first',
 'five',
 'fortun',
 'four',
 'free',
 'freedom',
 'french',
 'gdp',
 'global',
 'go',
 'good',
 'got',
 'grab',
 'great',
 'greek',
 'growth',
 'handinhand',
 'histori',
 'incorrect',
 'independ',
 'india',
 'invad',
 'lack',
 'land',
 'level',
 'life',
 'loot',
 'lucki',
 'materi',
 'mileston',
 'militari',
 'mind',
 'mogul',
 'must',
 'nation',
 'nuclear',
 'nurtur',
 'one',
 'onward',
 'opportun',
 'othersthat',
 'peopl',
 'percent',
 'portugues',
 'poverti',
 'power',
 'prakash',
 'professor',
 'protect',
 'rate',
 'recognis',
 'respect',
 'sarabhai',
 'satish',
 'second',
 'see',
 'selfassur',
 'selfconfid',
 'selfreli',
 'space',
 'stand',
 'start',
 'strength',
 'str

In [15]:
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(corpus).toarray()
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [16]:
TF_IDF = pd.DataFrame()
TF_IDF['Corpus'] = list(word for word in corpus)
TF_IDF['Vectorization'] = [vector for vector in X]

TF_IDF.head(10)

Corpus                                      Vectorization
0         gdp  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1        area  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...
2    thousand  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
3       today  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
4          go  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5         way  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6        life  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7       fifti  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
8       build  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9  othersthat  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [17]:
TF_IDF.iloc[1]

Corpus                                                        area
Vectorization    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, ...
Name: 1, dtype: object

In [18]:
TF_IDF.iloc[1][1]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# **3. Word2Vec:**

In [49]:
sentences = sent_tokenize(paragraph.lower())
sentences = [word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
  sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [51]:
model = Word2Vec(sentences, min_count=1)
words = model.wv.vocab
# words

similar_word = model.wv.most_similar('gdp')
similar_word

[('invaded', 0.31383001804351807),
 ('nurture', 0.261557400226593),
 ('terms', 0.2555462718009949),
 ('war', 0.19862303137779236),
 ('yet', 0.18631719052791595),
 ('lucky', 0.17741608619689941),
 ('self-confidence', 0.1680554747581482),
 ('years', 0.16767096519470215),
 ('economic', 0.16595402359962463),
 ('10', 0.16481947898864746)]